name: CD to Render
on:
  workflow_run:
    workflows: ["CI - Build and Test"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test # Skip tests as they are run in CI

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotel-management-system
          path: build/libs/*.jar

      - name: Extract short commit SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Trigger Render Deploy with GitHub version
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"environment_variables": {"APP_VERSION": "build-${{ github.run_number }}-${{ steps.sha.outputs.sha_short }}"}}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}

